config/routes.rb
Rails.application.routes.draw do
  resource :session, only: %i[new create destroy]
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")

  resources :products

  resources :chats, only: %i[index show] do
    resources :messages, only: %i[create]
  end

  get "/events/sse" => "events#sse"
  match "/events/websocket" => "events#websocket", via: %i[get connect]

  root "currencies#history"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :user

  has_many :messages, dependent: :destroy

  after_create_commit do
    Message.create!(chat: self, role: :system, content: "Hello! How can I help you?")
  end
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chat

  enum :role, { system: 0, user: 10 }

  scope :latest_last, -> { order(created_at: :asc) }
end

app/models/product.rb
class Product < ApplicationRecord
  has_many_attached :images
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :email, presence: true, uniqueness: true
  validates :name, presence: true

  normalizes :email, with: -> { _1.strip.downcase }

  has_many :chats, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  # allow_browser versions: :modern
  include Authentication
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  before_action :authenticate_user!

  def index
    @chat = Current.user.chats.create!
    redirect_to @chat
  end

  def show
    @chat = Current.user.chats.find(params[:id])
    @messages = @chat.messages.latest_last
  end
end

app/controllers/concerns/authentication.rb
module Authentication
  extend ActiveSupport::Concern

  included do
    helper_method :current_user, :user_signed_in?
  end

  def sign_in(user)
    Current.user = user
    cookies.encrypted.permanent[:user_id] = user.id
  end

  def sign_out(user)
    Current.user = nil
    reset_session
    cookies.delete(:user_id)
  end

  def authenticate_user!
    if current_user.blank?
      redirect_to new_session_path, alert: "You need to sign in to continue."
    end
  end

  private

  def current_user
    Current.user ||= authenticate_user_from_session
  end

  def user_signed_in?
    current_user.present?
  end

  def authenticate_user_from_session
    User.find_by(id: cookies.encrypted[:user_id])
  end
end

app/controllers/currencies_controller.rb
class CurrenciesController < ApplicationController
  def history
    base_currency = params[:base_currency] || "USD"
    @currency_map = {
      "USD" => "United States Dollar",
      "EUR" => "Euro",
      "JPY" => "Japanese Yen",
      "GBP" => "British Pound Sterling",
      "AUD" => "Australian Dollar",
      "CAD" => "Canadian Dollar",
      "INR" => "Indian Rupee",
      "CHF" => "Swiss Franc",
      "CNY" => "Chinese Yuan"
    }

    uri = URI("https://api.currencyapi.com/v3/latest")
    uri.query = URI.encode_www_form({
      "base_currency" => base_currency,
      "currencies" => (@currency_map.keys - [ base_currency ]).join(",")
    })

    response = Net::HTTP.start(uri.hostname, uri.port, use_ssl: true) do |http|
      http.get(uri, "apikey" => ENV.fetch("CURRENCY_API_KEY"))
    end

    @data = JSON.parse(response.body)["data"]
  end
end

app/controllers/events_controller.rb
require "async/websocket/adapters/rails"

class EventsController < ApplicationController
  before_action :authenticate_user!

  EVENT_STREAM_HEADERS = {
    "content-type" => "text/event-stream",
    "cache-control" => "no-cache",
    "last-modified" => Time.now.httpdate
  }

  def sse
    client = Redis.new
    user_id = Current.user.id

    body = proc do |stream|
      client.subscribe("user_#{user_id}_streams") do |on|
        on.message do |_, message|
          stream.write("data: #{message}\n\n")
        end
      end
    ensure
      stream.close
    end

    self.response = Rack::Response[200, EVENT_STREAM_HEADERS.dup, body]
  end

  def websocket
    client = Redis.new
    user_id = Current.user.id

    self.response = Async::WebSocket::Adapters::Rails.open(request) do |connection|
      subscription_task = Async do
        client.subscribe("user_#{user_id}_streams") do |on|
          on.message do |_, message|
            connection.send_text(message)
            connection.flush
          end
        end
      end

      while (message = connection.read)
        Rails.logger.info "Message from client: #{message}"
      end
    rescue Errno::EPIPE, Errno::ECONNRESET, IOError, Protocol::WebSocket::ClosedError
    ensure
      subscription_task&.stop
    end
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  include ActionView::RecordIdentifier

  before_action :authenticate_user!

  def create
    @chat = Current.user.chats.find(params[:chat_id])
    @message = @chat.messages.create!(message_params.merge(role: "user"))
    @user = Current.user

    Async do |task|
      stream_to_chat
    end

    head :ok
  end

  private

  def stream_to_chat
    add_message_to_chat(@message)
    stream_response
  end

  def add_message_to_chat(message)
    data = turbo_stream.append(
      "#{dom_id(@chat)}_messages",
      partial: "message",
      locals: { message: message }
    )
    publish_to_redis(data)
  end

  def stream_response
    response_message = @chat.messages.create!(role: "system", content: "")
    add_message_to_chat(response_message)
    openai_client.chat(
      parameters: {
          model: "gpt-3.5-turbo",
          messages: [ { role: "user", content: @message.content } ],
          temperature: 0.7,
          stream: proc do |chunk, _bytesize|
              begin
                response_message.content += chunk.dig("choices", 0, "delta", "content")
                response_message.save!
              rescue
              end
              replace_message_in_chat(response_message)
          end
    })
  end

  def replace_message_in_chat(message)
    data = turbo_stream.update(
      dom_id(message),
      partial: "message",
      locals: { message: message }
    )
    publish_to_redis(data)
  end


  def publish_to_redis(data)
    data.gsub!("\n", "")
    Redis.new.publish("user_#{@user.id}_streams", data)
  end

  def message_params
    params.require(:message).permit(:content)
  end

  def openai_client
    OpenAI::Client.new(
      access_token: ENV.fetch("OPENAI_API_KEY"),
      log_errors: true
    )
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to @product, notice: "Product was successfully created."
    else
      render :new
    end
  end

  def show
    @product = Product.find(params[:id])
  end

  private

  def product_params
    params.require(:product).permit(:name, images: [])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    if (user = User.authenticate_by(authentication_params))
      sign_in user
      redirect_to root_path, notice: "You are now signed in."
    else
      render :new, status: :unprocessable_entity, alert: "Invalid email or password."
    end
  end

  def destroy
    sign_out current_user
    redirect_to root_path, notice: "You are no longer signed in."
  end

  private

  def authentication_params
    {email: params[:email], password: params[:password]}
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/chats/_scroll.html.erb
<script>
  function throttle(func, limit) {
    let inThrottle;
    return function() {
        let context = this;
        let args = arguments;
        if (!inThrottle) {
            func.apply(context, args);
            inThrottle = true;
            setTimeout(() => inThrottle = false, limit);
        }
    }
  }


  function scrollToBottom() {
    let element = document.querySelector("#chat-messages-container");
    element.scrollTo({ top: element.scrollHeight, behavior: "smooth" });
  }

  const debouncedScrollToBottom = throttle(scrollToBottom, 300);

  document.addEventListener(
    "turbo:before-stream-render",
    debouncedScrollToBottom
  );
</script>

app/views/chats/show.html.erb
<div class="flex flex-col h-screen">
  <header class="bg-gray-900 text-white py-4 px-6">
    <h1 class="text-2xl font-bold">Chat App</h1>
  </header>
  <div class="flex-1 bg-gray-100 dark:bg-gray-800 p-6 overflow-y-auto" id="chat-messages-container">
    <div class="space-y-4">
      <%= tag.div id: dom_id(@chat) + "_messages"  do %>
        <%= render @messages %>
      <% end %>
    </div>
  </div>
  <%= form_with(model: Message.new, url: chat_messages_path(@chat), data: { controller: 'chat--form', action: 'turbo:submit-end->chat--form#reset' }) do |form| %>
    <div class="bg-gray-200 dark:bg-gray-900 p-4 flex items-center">
      <%= form.text_area :content,
        class: "flex-1 bg-white dark:bg-gray-800 text-gray-800 dark:text-gray-200 rounded-lg py-2 px-4 focus:outline-none focus:ring-2 focus:ring-blue-500",
        placeholder: "Type your message...",
        rows: 2
      %>
      <button class="bg-blue-500 text-white rounded-lg py-2 px-4 ml-4 hover:bg-blue-600 focus:outline-none focus:ring-2 focus:ring-blue-500">
        Send
      </button>
    </div>
  <% end %>
</div>

<%# <turbo-stream-source src="/events/sse"></turbo-stream-source> %>
<turbo-stream-source src="ws://localhost:3000/events/websocket"></turbo-stream-source>

<%= render "scroll" %>

app/views/currencies/history.html.erb
<!-- Table Section -->
<div class="max-w-[85rem] px-4 py-10 sm:px-6 lg:px-8 lg:py-14 mx-auto">
  <!-- Card -->
  <div class="flex flex-col">
    <div class="-m-1.5 overflow-x-auto">
      <div class="p-1.5 min-w-full inline-block align-middle">
        <div class="bg-white border border-gray-200 rounded-xl shadow-sm overflow-hidden dark:bg-neutral-900 dark:border-neutral-700">
          <!-- Header -->
          <div class="px-6 py-4 border-b border-gray-200 dark:border-neutral-700">
            <h2 class="text-xl font-semibold text-gray-800 dark:text-neutral-200">
              Latest Exchange Rates
            </h2>
            <p class="text-sm text-gray-600 dark:text-neutral-400">
              Current exchange rates for the most popular currencies vs USD.
            </p>
          </div>
          <!-- End Header -->

          <!-- Table -->
          <table class="min-w-full divide-y divide-gray-200 dark:divide-neutral-700">
            <thead class="bg-gray-50 dark:bg-neutral-800">
              <tr>
                <th scope="col" class="px-6 py-3 text-start whitespace-nowrap">
                  <span class="text-xs font-semibold uppercase tracking-wide text-gray-800 dark:text-neutral-200">
                    #
                  </span>
                </th>

                <th scope="col" class="px-6 py-3 text-start whitespace-nowrap min-w-64">
                  <span class="text-xs font-semibold uppercase tracking-wide text-gray-800 dark:text-neutral-200">
                    Currency
                  </span>
                </th>

                <th scope="col" class="px-6 py-3 text-start whitespace-nowrap">
                  <span class="text-xs font-semibold uppercase tracking-wide text-gray-800 dark:text-neutral-200">
                    Price
                  </span>
                </th>

              </tr>
            </thead>

            <tbody class="divide-y divide-gray-200 dark:divide-neutral-700">
              <% @data.values.each_with_index do |currency, index| %>
                <tr>
                  <td class="size-px whitespace-nowrap px-6 py-3">
                    <button type="button" class="flex items-center gap-x-2">
                      <svg class="flex-shrink-0 size-4 text-gray-800 dark:text-white" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2"/></svg>
                      <span class="text-sm text-gray-800 dark:text-neutral-200"><%= index + 1 %></span>
                    </button>
                  </td>
                  <td class="size-px whitespace-nowrap px-6 py-3">
                    <div class="flex items-center gap-x-3">
                      <span class="font-semibold text-sm text-gray-800 dark:text-white"><%= @currency_map.fetch(currency["code"]) %></span>
                      <span class="text-xs text-gray-500 dark:text-neutral-500"><%= currency["code"] %></span>
                    </div>
                  </td>
                  <td class="size-px whitespace-nowrap px-6 py-3">
                    <span class="text-sm text-gray-800 dark:text-white"><%= currency["value"] %></span>
                  </td>
                </tr>
              <% end %>

            </tbody>
          </table>
          <!-- End Table -->
        </div>
      </div>
    </div>
  </div>
  <!-- End Card -->
</div>
<!-- End Table Section -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "RailsConf Demo" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/_message.html.erb
<div id="<%= dom_id(message) %>" class="py-4">
 <% if message.user? %>
    <div class="flex items-start justify-end">
      <div class="bg-blue-500 text-white rounded-lg p-4 max-w-[80%]">
        <p><%= message.content %></p>
      </div>
    </div>
  <% else %>
    <div class="flex items-start">
      <div class="bg-white dark:bg-gray-700 text-gray-800 dark:text-gray-200 rounded-lg p-4 max-w-[80%]">
        <p><%= simple_format(message.content) %></p>
      </div>
    </div>
  <% end %>
</div>

app/views/products/index.html.erb
<div class="flex justify-center py-8">
  <ul class="list-disc list-inside space-y-4">
    <% @products.each do |product| %>
      <li class="text-lg font-semibold"><%= link_to product.name, product %></li>
    <% end %>
  </ul>
</div>

app/views/products/new.html.erb
<%= form_with(model: @product, local: true) do |form| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :images %>
    <%= form.file_field :images, multiple: true %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/show.html.erb
<div class="flex flex-col items-center">
  <h2 class="text-2xl font-bold mb-4"><%= @product.name %></h2>

  <div class="grid grid-cols-3 gap-4">
    <% @product.images.each do |image| %>
      <%= image_tag(rails_storage_proxy_path(image), class: "object-cover h-48 w-48") %>
    <% end %>
  </div>
</div>